### ISSUE TITLE
ユーザーデータの更新を簡単にする

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#100]
半年に１回データベースを更新する必要があるが、面倒なので更新を簡単にする。
可能なら自動的に更新できればいい。

**Comment by nozo-moto** [comment]
データ更新手順とかまとめて方がいいよね

**Comment by wancom** [comment]
本当は完全に自動化したいけど難しそう。
データ更新手順は軽くまとめてあるからもう少しわかりやすくするか、
いっそうのことスクリプトにまとめて叩いて管理者のIDとパスワードを
入力するだけで更新される感じにしたいかな。
多分そんなにかからないと思う。

**Comment by wancom** [comment]
できれば管理もフロントでできればパーフェクト。

**Comment by nozo-moto** [comment]
自動更新ボタンとかあったら楽そう

**Comment by wancom** [comment]
現実的な解決策として更新用スクリプトを用意します。
