### ISSUE TITLE
ボタンを連打させない

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#112]
重複投稿が発生しているので、一度ボタンを押したらボタンを無効化してレスポンスが来るまで押させない。

**Comment by wancom** [comment]
もしくはフラグで管理する。

**Comment by nozo-moto** [comment]
#116 が解決したら解決されるんじゃないかなって思ってたり

**Comment by nozo-moto** [comment]
これ解決した？
もしあれならrequestid発行して、冪等性を持たせるという手段もある

**Comment by wancom** [comment]
とりあえず、クリック直後にボタンを無効化させることで解決してるけど、
やっぱりサーバのレスポンスが遅い。
根拠のない憶測だけど、もしかしてSlackNotifyのリクエストで遅くなってるかも？
もしそうであればgoroutineで解決できると思う。
これはIssue立てた方が良さそう。
