### ISSUE TITLE
slack通知を非同期にする

### ISSUE THREAD

**Issue by nozo-moto** [AizuGeekDojo/EnterLeaveSystem#124]
サーバーのレスポンスが遅いため
https://github.com/AizuGeekDojo/EnterLeaveSystem/issues/112#issuecomment-470916729

**Comment by wancom** [comment]
どうやらSlackの方は処理が早いよう。
レスポンスが遅いのはまた違う理由らしい。
詳しくは #123

**Comment by wancom** [comment]
どっちみちSlackの通知を非同期にしてもいい気がする。
優先度低めで対応。

**Comment by nozo-moto** [comment]
結局遅いの変わってないんだっけか？
ローディングメニュー出す対応でどうだろう？

**Comment by wancom** [comment]
現在はAddLogリクエスト送信と同時に画面遷移してるから待ち時間は発生しなくなっているけど実際はレスポンスに多少時間がかかってる。
ただ時間がかかっている部分はSlackじゃなくてDB関係らしいからSlackの通知は非同期でなくても問題はない。

**Comment by wancom** [comment]
結局、フロント側の変更でAddLogのレスポンスを待たずに画面遷移をしているので影響がない。
ただ、Slackのリクエストが終わらないという自体を防ぐためにタイムアウトを設定した。
