### ISSUE TITLE
退室時のアンケートをショートカットで送信

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#133]
コメント入力時にCtrl+Enterなどでそのまま送信すると楽。

**Comment by wancom** [comment]
githubみたいに

**Comment by gpioblink** [comment]
エンターキーだけでも(control押さなくても)送信できてしまう

**Comment by gpioblink** [comment]
どうやら、同時押しじゃなくても反応するっぽい

**Comment by aizu-wakamatsu** [comment]
Comment was sent when I pressed Ctrl key without pressing Enter key.

**Comment by wancom** [comment]
原因が判明したので修正します。
(ついでにいくつか一緒に修正するかも)
