### ISSUE TITLE
カードリーダーがなくても動作するようにする

### ISSUE THREAD

**Issue by gpioblink** [AizuGeekDojo/EnterLeaveSystem#144]
カードリーダが刺さってないと、バックエンドエラーが発生し、カード忘れの機能も使えない

**Comment by wancom** [comment]
https://github.com/AizuGeekDojo/EnterLeaveSystem/blob/b339b203d456556a3636ab350830f01acdcc7444/cmd/handler/socket.go#L30
方針としてはここでpanicにせず、1分程度待ってからcontinueすると
クライアントは見かけがカード待ち状態になり影響が発生せず(カード忘れの機能で対応できる)、
サーバ側も基本機能には影響を及ぼさずにカードリーダーが見つかるまでリトライを繰り返しできる。

**Comment by nozo-moto** [comment]
ちゃんとやるならカードリーダーがうまく使えてない状態なのをWebSocket通じてフロントの方に伝えた方がいいかもね
WebSocket自体にはStatsuCodeみたいなのないから、送ってるJSONにエラーを加えたりなんなりして
