### ISSUE TITLE
Slack投げる時に死んでます…(Back)

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#67]

**Comment by nozo-moto** [comment]
アンケートのjsonの仕様はこちらなので、変更
```
{'Use': ['Other'], 'message': ''}
```

**Comment by nozo-moto** [comment]
余裕あったらAPIの仕様書き直してください

**Comment by hatobus** [comment]
とりあえず直した。

デバッグしてて思ったけどテストとか導入してみたいですね。

**Comment by nozo-moto** [comment]
@hatobus これ直した？
これ治れば通知まで修正完了する

**Comment by nozo-moto** [comment]
入室した時にアンケート結果表示する必要ないのでその辺よしなに

**Comment by hatobus** [comment]
https://github.com/AizuGeekDojo/EnterLeaveSystem/pull/75
