### ISSUE TITLE
フロント側のhttpページの欠落

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#82]
ビルド済みのものをリポジトリに含めておいてください。

**Comment by nozo-moto** [comment]
https://qiita.com/todogzm/items/db9f5f2cedf976379f84
リリース機能を使って、公開する様にします

**Comment by nozo-moto** [comment]
一度ビルドしてリリース機能にPushしないと行けないんだけど、ビルド用にCI使う？
個人のアカウントになっちゃうからなあという気持ちなんだけど
GeekDojoでCIサービスのアカデミックプランとか取れたりしないかなあ

**Comment by wancom** [comment]
CI使いたいけど使いたくないよね…
今後のメンテナンスが難しくなりそう。
Makefileを工夫して簡単にバイナリが作れるような仕組みの方がいいのかな？

**Comment by wancom** [comment]
確か一応GeekDojoのアカウントがあるからそれを使うという手もあるな。
@Aizu-Geek-Dojo

**Comment by nozo-moto** [comment]
@Aizu-Geek-Dojo使ってCircleCI登録するか

**Comment by wancom** [comment]
#157 で解決
