### ISSUE TITLE
指定時間に全員を退出させる

### ISSUE THREAD

**Issue by wancom** [AizuGeekDojo/EnterLeaveSystem#94]
退出処理を忘れる人が多いため夜中の12時などに全員を退出したと強制的にマークするようにする。

**Comment by wancom** [comment]
これは普通にsqlite3 database.db " update users set isenter=0;"をcrontab等に書いておけばいいと思います。

**Comment by nozo-moto** [comment]
https://gopkg.in/robfig/cron.v2
これ使ってサクッとかけそう
